/**
 * TESTE COMPLETO DO FLUXO DE GERAÇÃO DE IMAGENS
 * 
 * Testa TODOS os componentes end-to-end
 */

import { IntelligentImageEnhancer } from '../src/handlers/intelligent-image-enhancer';
import { extractReplicateImageInfo } from '../src/handlers/replicate-message-enhancer';
import { detectModelFromPrompt } from '../src/tools/replicate-enhanced';

// ============================================================================
// TEST DATA (Baseado no screenshot real)
// ============================================================================

const REAL_RESPONSE_FROM_BOT = `✅ Image generated! | Nanobanana Pro | $0.0200

https://replicate.delivery/pbxt/abc123def456.png

Generated by Ulfberht`;

const VARIATIONS_TO_TEST = [
  {
    name: 'Format atual (screenshot)',
    input: REAL_RESPONSE_FROM_BOT,
    expectedURL: 'https://replicate.delivery/pbxt/abc123def456.png',
    expectedModel: 'Nanobanana Pro',
    expectedShouldEnhance: true
  },
  {
    name: 'Formato com markdown',
    input: `Aqui está sua imagem:

![Image](https://replicate.delivery/xyz/image.png)

Modelo: Flux Schnell
Custo: $0.002`,
    expectedURL: 'https://replicate.delivery/xyz/image.png',
    expectedModel: 'Flux Schnell',
    expectedShouldEnhance: true
  },
  {
    name: 'Formato com prompt longo',
    input: `✅ Imagem gerada com sucesso!

Modelo: RealVisXL
Prompt: "Um viking épico segurando uma espada em chamas, fotorrealista, 8k"
Resolução: 1024x1024

https://replicate.delivery/test/viking.png`,
    expectedURL: 'https://replicate.delivery/test/viking.png',
    expectedModel: 'RealVisXL',
    expectedShouldEnhance: true
  },
  {
    name: 'URL genérica (não Replicate)',
    input: `Aqui está a imagem:

https://cdn.example.com/generated/image123.png

Gerada com AI Model`,
    expectedURL: 'https://cdn.example.com/generated/image123.png',
    expectedModel: 'AI Model',
    expectedShouldEnhance: true
  },
  {
    name: 'Mensagem sem imagem',
    input: `Olá! Como posso ajudar você hoje?`,
    expectedURL: null,
    expectedModel: null,
    expectedShouldEnhance: false
  },
  {
    name: 'URL mas não é imagem',
    input: `Confira este link: https://example.com/docs`,
    expectedURL: null,
    expectedModel: null,
    expectedShouldEnhance: false
  }
];

// ============================================================================
// TEST SUITE
// ============================================================================

async function runTests() {
  console.log('╔══════════════════════════════════════════════════════╗');
  console.log('║                                                      ║');
  console.log('║     🧪 IMAGE GENERATION FLOW - COMPLETE TEST 🧪      ║');
  console.log('║                                                      ║');
  console.log('╚══════════════════════════════════════════════════════╝\n');

  const enhancer = new IntelligentImageEnhancer();
  let totalTests = 0;
  let passedTests = 0;
  let failedTests = 0;

  for (const testCase of VARIATIONS_TO_TEST) {
    totalTests++;
    console.log(`\n📋 Test ${totalTests}: ${testCase.name}`);
    console.log('─'.repeat(60));

    try {
      // Test 1: URL Detection
      console.log('\n🔍 Step 1: URL Detection');
      const result = await enhancer.enhance(
        testCase.input,
        'test_user_123',
        'test_message_456'
      );

      // Validate URL detection
      if (testCase.expectedURL) {
        if (result.shouldEnhance && result.enhancedContent?.includes(testCase.expectedURL)) {
          console.log(`  ✅ URL detected: ${testCase.expectedURL}`);
        } else {
          console.log(`  ❌ URL not found! Expected: ${testCase.expectedURL}`);
          failedTests++;
          continue;
        }
      } else {
        if (!result.shouldEnhance) {
          console.log(`  ✅ Correctly skipped (no URL)`);
        } else {
          console.log(`  ❌ Should NOT have enhanced!`);
          failedTests++;
          continue;
        }
      }

      // Test 2: Model Detection
      console.log('\n🎨 Step 2: Model Detection');
      if (testCase.expectedModel) {
        if (result.enhancedContent?.includes(testCase.expectedModel)) {
          console.log(`  ✅ Model detected: ${testCase.expectedModel}`);
        } else {
          console.log(`  ⚠️  Model not exact match (may be ok)`);
        }
      }

      // Test 3: Button Creation
      console.log('\n🔘 Step 3: Button Creation');
      if (testCase.expectedShouldEnhance) {
        if (result.components && result.components.length > 0) {
          console.log(`  ✅ Buttons created: ${result.components.length} rows`);
          console.log(`     - Row 1: Regenerate, Remix, Video`);
          console.log(`     - Row 2: Ratio, Upscale, Download`);
        } else {
          console.log(`  ❌ No buttons created!`);
          failedTests++;
          continue;
        }
      }

      // Test 4: Enhanced Content
      console.log('\n📝 Step 4: Enhanced Content');
      if (testCase.expectedShouldEnhance && result.enhancedContent) {
        console.log(`  ✅ Content enhanced (${result.enhancedContent.length} chars)`);
        console.log(`  ✅ Contains "Content Creation Studio": ${result.enhancedContent.includes('Content Creation Studio')}`);
      }

      passedTests++;
      console.log('\n✅ TEST PASSED\n');

    } catch (error: any) {
      console.log(`\n❌ TEST FAILED: ${error.message}\n`);
      failedTests++;
    }
  }

  // ============================================================================
  // ADDITIONAL TESTS: Model Detection Accuracy
  // ============================================================================

  console.log('\n\n╔══════════════════════════════════════════════════════╗');
  console.log('║                                                      ║');
  console.log('║        🎯 MODEL DETECTION ACCURACY TEST 🎯           ║');
  console.log('║                                                      ║');
  console.log('╚══════════════════════════════════════════════════════╝\n');

  const modelTests = [
    { prompt: 'gera uma imagem com nanobanana pro', expected: 'nanobanana-pro' },
    { prompt: 'make it with flux schnell', expected: 'flux-schnell' },
    { prompt: 'use flux dev for best quality', expected: 'flux-dev' },
    { prompt: 'generate with sdxl', expected: 'sdxl' },
    { prompt: 'ultra realistic photo with epicrealism', expected: 'epicrealism' },
    { prompt: 'just make a simple image', expected: null }, // Should default to flux-schnell
  ];

  console.log('Testing smart model detection:\n');

  for (const test of modelTests) {
    const detected = detectModelFromPrompt(test.prompt);
    const expected = test.expected || 'flux-schnell'; // Default

    if (detected === expected) {
      console.log(`✅ "${test.prompt}"`);
      console.log(`   → Detected: ${detected}`);
      passedTests++;
    } else {
      console.log(`❌ "${test.prompt}"`);
      console.log(`   → Expected: ${expected}`);
      console.log(`   → Got: ${detected}`);
      failedTests++;
    }
    totalTests++;
  }

  // ============================================================================
  // ADDITIONAL TESTS: Legacy enhanceReplicateMessage
  // ============================================================================

  console.log('\n\n╔══════════════════════════════════════════════════════╗');
  console.log('║                                                      ║');
  console.log('║      📦 LEGACY ENHANCER COMPATIBILITY TEST 📦        ║');
  console.log('║                                                      ║');
  console.log('╚══════════════════════════════════════════════════════╝\n');

  console.log('Testing legacy extractReplicateImageInfo:\n');

  for (const testCase of VARIATIONS_TO_TEST.slice(0, 3)) {
    const info = extractReplicateImageInfo(testCase.input);
    totalTests++;

    if (testCase.expectedURL) {
      if (info && info.url === testCase.expectedURL) {
        console.log(`✅ "${testCase.name}"`);
        console.log(`   → URL: ${info.url}`);
        console.log(`   → Model: ${info.model}`);
        console.log(`   → Cost: $${info.cost}`);
        passedTests++;
      } else {
        console.log(`❌ "${testCase.name}"`);
        console.log(`   → Expected URL: ${testCase.expectedURL}`);
        console.log(`   → Got: ${info ? info.url : 'null'}`);
        failedTests++;
      }
    } else {
      if (!info) {
        console.log(`✅ "${testCase.name}" (correctly skipped)`);
        passedTests++;
      } else {
        console.log(`❌ "${testCase.name}" (should not have extracted)`);
        failedTests++;
      }
    }
  }

  // ============================================================================
  // FINAL REPORT
  // ============================================================================

  console.log('\n\n╔══════════════════════════════════════════════════════╗');
  console.log('║                                                      ║');
  console.log('║              📊 FINAL TEST REPORT 📊                 ║');
  console.log('║                                                      ║');
  console.log('╚══════════════════════════════════════════════════════╝\n');

  console.log(`Total Tests:  ${totalTests}`);
  console.log(`✅ Passed:    ${passedTests} (${((passedTests / totalTests) * 100).toFixed(1)}%)`);
  console.log(`❌ Failed:    ${failedTests} (${((failedTests / totalTests) * 100).toFixed(1)}%)`);

  if (failedTests === 0) {
    console.log('\n🎉🎉🎉 ALL TESTS PASSED! 🎉🎉🎉\n');
    console.log('✅ URL Detection: Working');
    console.log('✅ Model Detection: Working');
    console.log('✅ Button Creation: Working');
    console.log('✅ Enhanced Content: Working');
    console.log('✅ Smart Detection: Working');
    console.log('✅ Legacy Support: Working');
  } else {
    console.log('\n❌ SOME TESTS FAILED ❌\n');
    console.log('Check the output above for details.');
  }

  console.log('\n' + '═'.repeat(60) + '\n');
}

// Run tests
runTests().catch(console.error);
